// Frankrijk: energie, DPE, elektriciteit, renovatiesubsidies, bouw, overige transactiekosten.
import { VD_ELEC, DOOR_ELEC } from './constanten.mjs';

export const FR_ENERGIE = [

// --------------------------------------------------------------- DPE
{ id: 'p.fr.dpe.primaire_energiefactor_elektriciteit', nl: 'Primaire-energiefactor elektriciteit', fr: 'Coefficient d energie primaire, electricite', off: 'Coefficient de conversion en energie primaire',
  reg: 'fr.dpe', klasse: 'overheid_vastgesteld', effect: 'bepaalt_grondslag', eh: 'factor', jaar: '2026', van: '2026-01-01',
  kn: 'arrete du 13 aout 2025, in werking per 1 januari 2026', bs: 'secundair: het arrete is in de repo genoemd maar niet als vindplaats vastgelegd',
  inst: 'Ministere de la transition ecologique', freq: 'meerjaarlijks', lw: '2026-01-01',
  in: [[ 'energieportaal', 'engine/dpe.js:47', '1,9', false ],
       [ 'if-mobiel', 'engine/dpe.js:47 (byte-identieke kopie)', '1,9', false ]],
  opm: 'Het arrete staat genoemd, maar er is geen verificatiedatum en geen vindplaats. Peil waardeert dat niet stilzwijgend op tot een vastgestelde waarde.' },

{ id: 'p.fr.dpe.co2_emissiefactoren', nl: 'CO2-emissiefactoren per energiedrager', fr: 'Facteurs d emission de CO2 par energie', off: null,
  reg: 'fr.dpe', klasse: 'overheid_vastgesteld', effect: 'bepaalt_grondslag', eh: 'kg CO2 per kWh', jaar: '2026',
  freq: 'meerjaarlijks',
  in: [[ 'energieportaal', 'engine/dpe.js:63-64', 'elec 0,079; gas 0,227; fioul 0,324; propaan 0,272; pellet en hout 0,030; petroleum 0,324', false ],
       [ 'if-mobiel', 'engine/dpe.js:63-64 (byte-identieke kopie)', 'identiek', false ]] },

{ id: 'p.fr.dpe.klassegrenzen', nl: 'DPE-klassegrenzen voor energie en CO2', fr: 'Seuils des classes DPE, energie et CO2', off: 'Etiquettes du diagnostic de performance energetique',
  reg: 'fr.dpe', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'kWh/m2 en kg CO2/m2', jaar: '2026',
  freq: 'meerjaarlijks',
  in: [[ 'energieportaal', 'engine/dpe.js:73-88', 'energie A 70 tot F 420 kWh per m2; CO2 A 6 tot F 100 kg per m2', false ],
       [ 'if-mobiel', 'engine/dpe.js:73-88 (byte-identieke kopie)', 'identiek', false ]] },

// --------------------------------------------------------------- energiekentallen
{ id: 'p.fr.energie.graaddagen_per_klimaatzone', nl: 'Graaddagen en referentietemperatuur per klimaatzone', fr: 'Degres-jours et temperature de reference par zone', off: null,
  reg: 'fr.energie', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'HDD en graden C', jaar: '2026',
  freq: 'zelden',
  in: [[ 'energieportaal', 'engine/dpe.js:28-33', 'med 1400/12, ouest 1900/10, paris 2200/7, centre 2500/6, est 2800/5, mont 3400/2', false ],
       [ 'if-mobiel', 'engine/dpe.js:28-33 (byte-identieke kopie)', 'identiek', false ],
       [ 'warmteverlies-calculator', 'engine/engine.js:6-11', 'identiek, met koeldagen en zwembadtemperatuur erbij', false ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:4', 'identiek', false ]],
  opm: 'Vier aangesloten tools, identieke waarden. if-mobiel bevat een byte-identieke kopie van de hele engine van energieportaal; dat is een kopie, geen verwijzing, en dus een onderhoudsrisico.' },

{ id: 'p.fr.energie.koeldagen_en_zwembadtemperatuur', nl: 'Koeldagen en zwembadtemperatuur per klimaatzone', fr: 'Degres-jours de refroidissement et temperature de piscine', off: null,
  reg: 'fr.energie', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'CDD en graden C', jaar: '2026',
  freq: 'zelden',
  in: [[ 'warmteverlies-calculator', 'engine/engine.js:6-11', 'med 700/22, ouest 350/20, paris 250/19, centre 200/19, est 150/18, mont 50/17', false ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:4', 'identiek', false ]] },

{ id: 'p.fr.energie.pv_opbrengst_per_klimaatzone', nl: 'PV-opbrengst per klimaatzone', fr: 'Productible photovoltaique par zone', off: null,
  reg: 'fr.energie', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'kWh per kWp per jaar', jaar: '2026',
  freq: 'zelden',
  in: [[ 'energieportaal', 'engine/engine.js:14', 'med 1450, ouest 1250, paris 1150, centre 1200, est 1150, mont 1100', false ],
       [ 'if-mobiel', 'engine/engine.js:14 (byte-identieke kopie)', 'identiek', false ],
       [ 'warmteverlies-calculator', 'engine/engine.js:14', 'identiek', false ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:5', 'identiek', false ]] },

{ id: 'p.fr.energie.u_waarden_isolatieniveau', nl: 'U-waarden per isolatieniveau', fr: 'Coefficients U par niveau d isolation', off: null,
  reg: 'fr.energie', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'W/m2K', jaar: '2026',
  freq: 'zelden',
  in: [[ 'energieportaal', 'engine/engine.js:62-66', 'dak 3,0 / 0,5 / 0,25 / 0,15; vloer 2,2 / 1,2 / 0,8 / 0,3; raam 5,5 / 2,8 / 1,6 / 1,0', true ],
       [ 'if-mobiel', 'engine/engine.js:62-66 (byte-identieke kopie)', 'identiek aan energieportaal', true ],
       [ 'warmteverlies-calculator', 'engine/engine.js:63-66', 'identiek aan energieportaal', true ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:15', 'dak 3,0 / 0,5 / 0,2 / 0,1; vloer 1,2 / 0,5 / 0,3 / 0,18; raam 5,8 / 2,9 / 1,7 / 0,8', true ]],
  opm: 'De oudste calculator hanteert andere U-waarden voor dak, vloer en raam. Alleen de muurwaarden zijn in alle vier gelijk. Waar die oude calculator nog is ingebed, geeft hij andere uitkomsten.' },

{ id: 'p.fr.energie.apparaatverbruik_per_jaar', nl: 'Apparaatverbruik per jaar', fr: 'Consommation annuelle par appareil', off: null,
  reg: 'fr.energie', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'kWh/jaar', jaar: '2026',
  freq: 'zelden',
  in: [[ 'warmteverlies-calculator', 'engine/engine.js:17-23', 'koelkast 250, wassen 220, vaatwasser 160, IT 150, tv 120, klein 150, verlichting 180', true ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:6', 'koelkast 250, wassen 220, vaatwasser 180, oven 120, tv 100, IT 100, verlichting 200', true ]],
  opm: 'Vier van de zeven posten wijken af en de indeling verschilt. Koelkast en wassen zijn gelijk.' },

{ id: 'p.fr.energie.standaardprijzen_invoer', nl: 'Standaard energieprijzen als invulwaarde', fr: 'Prix de l energie par defaut', off: null,
  reg: 'fr.energie', klasse: 'gebruikersinvoer', effect: 'bepaalt_grondslag', eh: 'EUR per eenheid', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'energieportaal', 'engine/engine.js:26', 'elec 0,25 EUR/kWh; gas 1,20 EUR/m3; fioul 1,15 EUR/L; pellet 0,60 EUR/kg; hout 85 EUR/stere; propaan 1,80 EUR/L; petroleum 2,00 EUR/L', true ],
       [ 'if-mobiel', 'engine/engine.js:26 (byte-identieke kopie)', 'identiek', true ],
       [ 'warmteverlies-calculator', 'engine/engine.js:26', 'identiek', true ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:8', 'identiek', true ]],
  opm: 'Invulwaarden die de gebruiker kan overschrijven. Ze wijken af van de referentieprijzen met bron in p.fr.energie.referentieprijzen: propaan staat hier op 1,80 en daar op 1,90 EUR per liter, elektriciteit hier op 0,25 en daar op 0,194 EUR per kWh. Zolang de gebruiker niets invult, rekenen de tools met de invulwaarde.' },

{ id: 'p.fr.energie.referentieprijzen', nl: 'Referentie-energieprijzen met peildatum', fr: 'Prix de reference de l energie', off: null,
  reg: 'fr.energie', klasse: 'marktindex', effect: 'bepaalt_grondslag', eh: 'EUR per eenheid', jaar: '2026',
  kn: 'CRE voor elektriciteit en gas, DGEC Pegase voor propaan en stookolie', bs: 'secundair: waarden in de tool met een refDate per waarde, niet per waarde tegen de publicatie gelegd',
  inst: 'CRE en DGEC', freq: 'doorlopend', resp: 'Anton Noe, Communities Abroad', houd: '2026-12-16',
  in: [[ 'energieportaal', 'api/prices.js:15-22', 'elec 0,194 EUR/kWh (CRE, feb 2026); gas 0,1051 EUR/kWh PCI (CRE, apr 2026); fioul 1,19 EUR/L (mrt 2026); pellet 0,60 EUR/kg (Q1 2026); hout 85 EUR/stere (2025); propaan 1,90 EUR/L; petroleum 2,00 EUR/L', false ]],
  opm: 'Elektriciteit en gas worden live bij de CRE opgehaald, de rest staat vast in het bestand. De waarden dragen elk een eigen refDate, van 2025 tot april 2026. Peil kan er daarom geen enkele verificatiedatum aan hangen. Splitsen per energiedrager is nodig; dat staat in de gatenlijst.' },

{ id: 'p.fr.energie.omrekenfactoren_kwh', nl: 'Omrekenfactoren naar kWh per eenheid', fr: 'Facteurs de conversion en kWh', off: null,
  reg: 'fr.energie', klasse: 'afgeleid', effect: 'bepaalt_grondslag', eh: 'kWh per eenheid', jaar: '2026',
  freq: 'zelden',
  in: [[ 'energieportaal', 'engine/engine.js:28', 'gas 10, fioul 10, pellet 5, hout 1800, propaan 7,1, petroleum 10', false ],
       [ 'if-mobiel', 'engine/engine.js:28 (byte-identieke kopie)', 'identiek', false ],
       [ 'warmteverlies-calculator', 'engine/engine.js:28', 'identiek', false ],
       [ 'Energiecalculator-Frankrijk-door-Nederlanders.fr', 'script.js:10', 'identiek', false ],
       [ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:156', 'hout 1800 kWh per stere', false ]] },

{ id: 'p.fr.energie.houtenergie_per_stere', nl: 'Energie-inhoud hout per stere', fr: 'Contenu energetique du bois par stere', off: null,
  reg: 'fr.energie', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'kWh/stere', jaar: '2026',
  freq: 'zelden',
  in: [[ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:156', '1800 kWh droog hardhout, 1400 kWh zachthout', false ]] },

{ id: 'p.fr.energie.verouderingsdrempel_prijzen', nl: 'Verouderingsdrempel voor de energieprijzen', fr: 'Seuil d obsolescence des prix', off: null,
  reg: 'fr.energie', klasse: 'afgeleid', effect: 'informatief', eh: 'dagen', jaar: '2026',
  freq: 'onbekend',
  in: [[ 'energieportaal', 'api/prices.js:7', '120', false ]],
  opm: 'Eigen bewaking van de tool: boven de 120 dagen meldt de prijsmodule dat de prijs veroudert.' },

// --------------------------------------------------------------- elektriciteit, dossier-elektriciteit-if
{ id: 'p.fr.elec.consuel_geel_elektronisch', nl: 'Consuel-tarief attestation geel, elektronisch', fr: 'Tarif Consuel, attestation jaune, voie electronique', off: 'Bareme Consuel',
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: 144.67, wv: '144,67 euro', van: '2025-09-02',
  kn: 'barema bij arrete van 4 augustus 2015, geindexeerd met 0,64 procent per 2 september 2025',
  bs: 'secundair: barema van Consuel, het arrete zelf niet gelezen',
  inst: 'Consuel', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks', lw: '2025-09-02',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h8.md:12, 51 en 99', '144,67', false ]] },

{ id: 'p.fr.elec.consuel_overige_formulieren', nl: 'Consuel-tarieven overige formulieren', fr: 'Tarifs Consuel, autres attestations', off: 'Bareme Consuel',
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: { geel_papier: 146.15, groen: 76.37, blauw: 201.17, violet: 230.32 },
  wv: 'geel op papier 146,15; groen 76,37; blauw 201,17; violet 230,32 euro', van: '2025-09-02',
  kn: 'barema van Consuel, geverifieerd op 4 juli 2026', bs: 'secundair: barema van Consuel, het arrete zelf niet gelezen',
  inst: 'Consuel', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks', lw: '2025-09-02',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h8.md:51', 'geel papier 146,15; groen 76,37; blauw 201,17; violet 230,32', false ]] },

{ id: 'p.fr.elec.consuel_contre_visite', nl: 'Consuel contre-visite', fr: 'Consuel, contre-visite', off: 'Bareme Consuel',
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: 232.13, wv: '232,13 euro', van: '2025-09-02',
  kn: 'barema van Consuel, geverifieerd op 4 juli 2026', bs: 'secundair: barema van Consuel, het arrete zelf niet gelezen',
  inst: 'Consuel', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h8.md:51 en 99', '232,13', false ]] },

{ id: 'p.fr.elec.consuel_indexering', nl: 'Indexering van het Consuel-barema', fr: 'Indexation du bareme Consuel', off: null,
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'procent', jaar: '2026',
  st: 'vastgesteld', w: 0.64, wv: '0,64 procent per 2 september 2025', van: '2025-09-02',
  kn: 'indexering van het barema per 2 september 2025', bs: 'secundair: mededeling van Consuel, de onderliggende beslissing niet gelezen',
  inst: 'Consuel', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks', lw: '2025-09-02',
  pub: 'Consuel indexeert het barema doorgaans begin september',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h8.md:48 en 99', '0,64 procent per 02-09-2025', false ]] },

{ id: 'p.fr.elec.tariefoptiewissel_zonder_linky', nl: 'Tariefoptiewissel zonder Linky', fr: 'Changement d option tarifaire sans Linky', off: 'TURPE, prestation Enedis',
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: 56.72, wv: '56,72 euro; met Linky gratis',
  kn: 'catalogue des prestations Enedis, geverifieerd op 4 juli 2026', bs: 'secundair: prestatiecatalogus van Enedis, de CRE-deliberatie niet zelf gelezen',
  inst: 'Enedis', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h1.md:120', '56,72', false ]] },

{ id: 'p.fr.elec.beheerbijdrage_weigeren_linky', nl: 'Beheerbijdrage bij weigeren van de Linky-meter', fr: 'Contribution de gestion en cas de refus du compteur Linky', off: 'TURPE 7',
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: { per_twee_maanden_ht: 6.48, opslag_geen_meterstand_ht: 4.14 },
  wv: '6,48 euro exclusief btw per twee maanden, plus 4,14 euro exclusief btw bij meer dan een jaar geen meterstand',
  van: '2025-08-01',
  kn: 'TURPE 7, deliberatie van de CRE 2025-78', bs: 'secundair: de deliberatie is genoemd maar niet als vindplaats vastgelegd',
  inst: 'CRE en Enedis', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks', lw: '2025-08-01',
  pub: 'de CRE stelt het TURPE-tarief jaarlijks per 1 augustus bij',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h1.md:125', '6,48 EUR HT per twee maanden, plus 4,14 EUR HT', false ]] },

{ id: 'p.fr.elec.wijziging_puissance_souscrite', nl: 'Administratieve wijziging van de puissance souscrite', fr: 'Changement de puissance souscrite', off: 'Catalogue des prestations Enedis',
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: 4.28, wv: 'circa 4,28 euro inclusief btw',
  kn: 'catalogue des prestations Enedis', bs: 'secundair: prestatiecatalogus van Enedis, de CRE-deliberatie niet zelf gelezen',
  inst: 'Enedis', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'jaarlijks',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h1.md:126', 'circa 4,28 EUR TTC', false ]] },

{ id: 'p.fr.elec.vermogenstrappen', nl: 'Vermogenstrappen en aansluitgrenzen', fr: 'Paliers de puissance et limites de raccordement', off: null,
  reg: 'fr.elec', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'kVA', jaar: '2026',
  st: 'vastgesteld', w: { abonnement_kva: [3, 6, 9, 12], monophase_max_kva: 12, triphase_max_kva: 36 },
  wv: 'abonnement 3, 6, 9 of 12 kVA; monophase maximaal 12 kVA; triphase tot 36 kVA',
  kn: 'Enedis, aansluitvoorwaarden, geverifieerd op 4 juli 2026', bs: 'secundair: voorwaarden van Enedis, de norm zelf niet gelezen',
  inst: 'Enedis', vd: VD_ELEC, vdoor: DOOR_ELEC, freq: 'zelden',
  in: [[ 'dossier-elektriciteit-if', 'hoofdstukken/h1.md:63 en 67', '3-6-9-12 kVA; monophase max 12 kVA; triphase tot 36 kVA', false ]] },

{ id: 'p.fr.diagnostics.geldigheid_diagnostic_electrique', nl: 'Geldigheid van het diagnostic electrique', fr: 'Duree de validite du diagnostic electrique', off: 'Art. R271-5 Code de la construction et de l habitation',
  reg: 'fr.diagnostics', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'jaren', jaar: '2026',
  st: 'vastgesteld', w: { verkoop_jaren: 3, verhuur_jaren: 6, verplicht_bij_installatie_ouder_dan_jaren: 15 },
  wv: '3 jaar bij verkoop, 6 jaar bij verhuur; verplicht bij een installatie ouder dan 15 jaar',
  url: 'https://www.service-public.fr/particuliers/vosdroits/F18692',
  kn: 'service-public.fr, fiche F18692', bs: 'secundair: samenvattende fiche van service-public.fr, het wetsartikel niet zelf gelezen',
  inst: 'Ministere de la transition ecologique', vd: VD_ELEC, vdoor: 'dossier-elektriciteit-if, verificatie/normverificatie.md',
  freq: 'zelden',
  in: [[ 'dossier-elektriciteit-if', 'verificatie/normverificatie.md:V9', '3 jaar verkoop, 6 jaar verhuur, 15 jaar ouderdomsgrens', false ]] },

// --------------------------------------------------------------- renovatie en subsidies
{ id: 'p.fr.tva.tarief_renovatie', nl: 'Btw-tarief energetische renovatiewerken', fr: 'Taux de TVA sur les travaux de renovation energetique', off: 'Art. 278-0 bis A CGI',
  reg: 'fr.tva', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'procent', jaar: '2026', van: '2025-03-01',
  freq: 'onregelmatig', lw: '2025-03-01',
  in: [[ 'energiebesparing-subsidie-en-fiscale-regelingen', 'script.js:193-206', '5,5 procent, naast 10 procent', false ],
       [ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:234', '5,5 procent bij RGE-installateur', false ]],
  uitz: ['Welk verlaagd tarief geldt, 5,5 of 10 procent, hangt af van de aard van de werken en van de kwalificatie van de installateur. Laat dat bij een concrete offerte door de aannemer bevestigen.'] },

{ id: 'p.fr.renov.ouderdomsgrens_woning', nl: 'Ouderdomsgrens van de woning voor verlaagd tarief en Eco-PTZ', fr: 'Anciennete du logement requise', off: null,
  reg: 'fr.renov', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'jaren', jaar: '2026',
  freq: 'zelden',
  in: [[ 'energiebesparing-subsidie-en-fiscale-regelingen', 'script.js:193', '2 jaar', false ]] },

{ id: 'p.fr.renov.maprimerenov_plafond', nl: 'MaPrimeRenov, plafondbedrag in de pagina', fr: 'MaPrimeRenov, plafond', off: null,
  reg: 'fr.renov', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'plafond', eh: 'EUR', jaar: '2026',
  freq: 'jaarlijks',
  in: [[ 'energiebesparing-subsidie-en-fiscale-regelingen', 'index.html:35', '24500', false ]],
  opm: 'Het plafond hangt af van het inkomenssegment en van het soort werk. Een enkel bedrag dekt dat niet.' },

{ id: 'p.fr.renov.ecoptz_maximum', nl: 'Eco-PTZ, maximum leenbedrag', fr: 'Eco-pret a taux zero, montant maximal', off: null,
  reg: 'fr.renov', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'plafond', eh: 'EUR', jaar: '2026',
  freq: 'meerjaarlijks',
  in: [[ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:233-234', 'tot 50000 euro renteloos', false ]] },

{ id: 'p.fr.renov.maprimerenov_budget', nl: 'MaPrimeRenov, budget en achterstand', fr: 'MaPrimeRenov, budget et arrieres', off: null,
  reg: 'fr.renov', klasse: 'indicatief', effect: 'informatief', eh: 'EUR en aantal', jaar: '2026',
  freq: 'jaarlijks',
  in: [[ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:237', '3,6 miljard euro budget 2026, 83000 onbehandelde dossiers uit 2025', false ]],
  opm: 'Geen rekenparameter maar een kental dat de AI-adviseur gebruikt om wachttijden te duiden.' },

{ id: 'p.fr.renov.maprimeadapt_maximum', nl: 'MaPrimeAdapt, maximaal aandeel van de kosten', fr: 'MaPrimeAdapt, part maximale des couts', off: null,
  reg: 'fr.renov', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'plafond', eh: 'procent', jaar: '2026',
  freq: 'jaarlijks',
  in: [[ 'ouderenzorg-fr', 'if-dossier/dossier-skelet.md:128', 'tot 70 procent van de kosten', false ]] },

{ id: 'p.fr.renov.richtprijzen_maatregelen', nl: 'Richtprijzen renovatiemaatregelen', fr: 'Prix indicatifs des travaux de renovation', off: null,
  reg: 'fr.renov', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'EUR', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:272-279', 'dakisolatie 25-50 EUR/m2; ITI 50-90; ITE 100-200; vloerisolatie 30-60; raam HR++ 400-800 per stuk; warmtepomp lucht-water 8000-15000; geothermisch 15000-25000; PV 3 kWp 5000-8000', false ]] },

{ id: 'p.fr.renov.besparing_per_graad', nl: 'Besparing per graad lagere binnentemperatuur', fr: 'Economie par degre de moins', off: null,
  reg: 'fr.renov', klasse: 'indicatief', effect: 'informatief', eh: 'procent', jaar: '2026',
  freq: 'zelden',
  in: [[ 'nlfr-ai-agent', 'knowledge/experts/energieportaal-ai-adviseur.md:286', 'circa 7 procent', false ]] },

// --------------------------------------------------------------- bouw en overige
{ id: 'p.fr.bouw.drempels_bijgebouw', nl: 'Oppervlaktedrempels voor een vrijstaand bijgebouw', fr: 'Seuils de surface pour une annexe', off: 'Art. R421-2 en R421-9 Code de l urbanisme',
  reg: 'fr.bouw', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'm2', jaar: '2026',
  freq: 'zelden',
  in: [[ 'bouwvergunningwijzer-frankrijk', 'docs/rule-matrix-v0.1.md:22-24', 'tot 5 m2 geen formaliteit; 5 tot 20 m2 declaration prealable; boven 20 m2 permis de construire', false ]],
  opm: 'Het brondocument meldt zelf dat de koppeling aan Legifrance-artikelen nog moet gebeuren.' },

{ id: 'p.fr.bouw.drempels_uitbreiding', nl: 'Oppervlaktedrempels voor een uitbreiding', fr: 'Seuils de surface pour une extension', off: 'Art. R421-14 en R431-2 Code de l urbanisme',
  reg: 'fr.bouw', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'm2', jaar: '2026',
  freq: 'zelden',
  in: [[ 'bouwvergunningwijzer-frankrijk', 'docs/rule-matrix-v0.1.md:27-29', 'buiten zone U tot 20 m2 DP; in zone U tot 40 m2 DP; boven 20 tot 40 m2 architectenplicht toetsen', false ]] },

{ id: 'p.fr.huur.boete_late_teruggave_borg', nl: 'Boete bij te late teruggave van de huurborg', fr: 'Majoration en cas de restitution tardive du depot de garantie', off: 'Art. 22 al. 5 loi 89-462',
  reg: 'fr.huur', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', eh: 'procent', jaar: '2026',
  kn: 'art. 22 al. 5 van wet 89-462 van 6 juli 1989', bs: 'secundair: wetsartikel genoemd in de brieftemplate, de tekst niet als vindplaats vastgelegd',
  freq: 'zelden',
  in: [[ 'briefhulp-fr', 'cache/verhuurder/borg/niveau-2.json:29', '10 procent van de kale maandhuur per begonnen maand', false ],
       [ 'briefhulp-fr', 'cache/verhuurder/borg/niveau-3.json:33 en 83', 'identiek', false ],
       [ 'briefhulp-fr', 'KLIKSTROMEN.md:233', '10 procent per maand vertraging', false ]] },

{ id: 'p.fr.telecom.max_verbrekingsvergoeding', nl: 'Maximale verbrekingsvergoeding telecom', fr: 'Indemnite de resiliation maximale', off: 'Art. L224-39 Code de la consommation',
  reg: 'fr.telecom', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', vt: 'plafond', eh: 'procent', jaar: '2026',
  kn: 'art. L224-39 Code de la consommation', bs: 'secundair: wetsartikel genoemd in de brieftemplate, de tekst niet als vindplaats vastgelegd',
  freq: 'zelden',
  in: [[ 'briefhulp-fr', 'cache/telecom/opzeg/niveau-1.json:25', '25 procent van het restant', false ]] },

{ id: 'p.fr.telecom.minimale_looptijd_binding', nl: 'Minimale looptijd voor opzegging met binding', fr: 'Duree minimale avant resiliation', off: 'Art. L224-28 Code de la consommation',
  reg: 'fr.telecom', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'maanden', jaar: '2026',
  freq: 'zelden',
  in: [[ 'briefhulp-fr', 'cache/telecom/opzeg/niveau-1.json:25', '12 maanden', false ]] },

{ id: 'p.fr.handel.forfaitaire_incassokosten', nl: 'Forfaitaire incassokosten bij te late betaling', fr: 'Indemnite forfaitaire de recouvrement', off: 'Art. L441-10 Code de commerce',
  reg: 'fr.handel', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR', jaar: '2026',
  freq: 'zelden',
  in: [[ 'briefhulp-fr', 'cache/werkgever/factuur/niveau-3.json:32', '40 euro', false ]] },

{ id: 'p.fr.efact.datum_ontvangstplicht', nl: 'Invoeringsdatum ontvangstplicht e-facturatie', fr: 'Date d entree en vigueur de l obligation de reception', off: 'Facturation electronique, calendrier legal',
  reg: 'fr.efact', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'datum', jaar: '2026',
  st: 'vastgesteld', w: '2026-09-01', wv: '1 september 2026', van: '2026-09-01',
  url: 'https://www.impots.gouv.fr/facturation-electronique', kn: 'impots.gouv.fr, facturation electronique, gecontroleerd 8 juli 2026',
  bs: 'primair', inst: 'DGFiP', vd: '2026-07-08', vdoor: 'e-facturatie-frankrijk, data/rules.ts',
  freq: 'onregelmatig',
  in: [[ 'e-facturatie-frankrijk', 'data/rules.ts:44-49', '1 september 2026', false ]],
  opm: 'Geldt tegelijk als uitgifteplicht voor grote ondernemingen.' },

{ id: 'p.fr.efact.datum_uitgifteplicht_pme', nl: 'Invoeringsdatum uitgifteplicht PME en TPE', fr: 'Date d entree en vigueur de l obligation d emission, PME et TPE', off: null,
  reg: 'fr.efact', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'datum', jaar: '2027',
  st: 'vastgesteld', w: '2027-09-01', wv: '1 september 2027', van: '2027-09-01',
  url: 'https://www.impots.gouv.fr/facturation-electronique', kn: 'impots.gouv.fr, facturation electronique, gecontroleerd 8 juli 2026',
  bs: 'primair', inst: 'DGFiP', vd: '2026-07-08', vdoor: 'e-facturatie-frankrijk, data/rules.ts',
  freq: 'onregelmatig',
  aank: { datum: '2027-09-01', omschrijving: 'Uitgifteplicht gaat gelden voor PME en TPE', bron: 'impots.gouv.fr, facturation electronique' },
  in: [[ 'e-facturatie-frankrijk', 'data/rules.ts:54-56', '1 september 2027', false ]] },

{ id: 'p.fr.efact.grens_tpe', nl: 'Grens voor een TPE', fr: 'Seuil de la tres petite entreprise', off: 'Categories d entreprises, INSEE',
  reg: 'fr.efact', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR en aantal', jaar: '2026',
  st: 'vastgesteld', w: { medewerkers_minder_dan: 10, omzet_of_balanstotaal_max_eur: 2000000 },
  wv: 'minder dan 10 medewerkers en maximaal 2 miljoen euro omzet of balanstotaal',
  kn: 'INSEE, categories d entreprises; gecontroleerd 8 juli 2026',
  bs: 'secundair: definitie van de INSEE, het decreet niet zelf gelezen',
  inst: 'INSEE', vd: '2026-07-08', vdoor: 'e-facturatie-frankrijk, data/rules.ts', freq: 'zelden',
  in: [[ 'e-facturatie-frankrijk', 'data/rules.ts:103', 'minder dan 10 medewerkers en maximaal 2 miljoen euro', false ]] },
];
