// Frankrijk, fiscaal en sociaal op inkomen en vermogen.
import { VD_FKAI, DOOR_FKAI, VD_VT, DOOR_VT, VT_PV_URL, oud } from './constanten.mjs';

export const FR_FISCAAL = [

// --------------------------------------------------------------- CSG, CRDS, CASA
{ id: 'p.fr.csg.tarief_per_regime', nl: 'CSG, CRDS en CASA per regime op pensioen', fr: 'CSG, CRDS et CASA par taux sur les pensions', off: 'Taux zéro, taux réduit, taux médian, taux normal',
  reg: 'fr.csg', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026',
  st: 'vastgesteld',
  w: [{ naam: 'taux zéro', csg: 0, crds: 0, casa: 0, totaal: 0, csg_aftrekbaar: 0 },
      { naam: 'taux réduit', csg: 0.038, crds: 0.005, casa: 0, totaal: 0.043, csg_aftrekbaar: 0.038 },
      { naam: 'taux médian', csg: 0.066, crds: 0.005, casa: 0.003, totaal: 0.074, csg_aftrekbaar: 0.042 },
      { naam: 'taux normal', csg: 0.083, crds: 0.005, casa: 0.003, totaal: 0.091, csg_aftrekbaar: 0.059 }],
  wv: '0 procent, 4,3 procent, 7,4 procent of 9,1 procent, afhankelijk van het revenu fiscal de référence',
  url: 'https://www.service-public.fr/particuliers/vosdroits/F2971',
  kn: 'service-public.fr, fiche F2971, CSG et CRDS sur les revenus d\'activité et de remplacement; art. L136-1 en L136-8 CSS',
  bs: 'secundair: samenvattende fiche van service-public.fr, de wetsartikelen niet zelf gelezen',
  inst: 'Urssaf en DGFiP', vd: '2026-06-01', vdoor: DOOR_FKAI,
  freq: 'jaarlijks', lw: '2026-01-01', pub: 'service-public.fr werkt de fiche bij in het voorjaar',
  in: [[ 'financieel-kompas-ai', 'config.json:87-116', 'vier regimes, 0 / 0,043 / 0,074 / 0,091', false ]],
  uitz: ['Overgang naar een hoger tarief geldt pas na twee opeenvolgende jaren overschrijding. Die overgangsregel is bewust niet ingebouwd. Wie in het overgangsjaar zit, legt de eigen avis d\'imposition voor aan een belastingadviseur.'],
  test: { invoer: 'pensioen 25.000 euro, taux normal', verwachte_uitkomst: '2.275 euro CSG, CRDS en CASA', toelichting: '25.000 maal 0,091.' },
  opm: 'Van de CSG is per regime slechts een deel aftrekbaar voor de inkomstenbelasting: 0, 3,8, 4,2 of 5,9 procent. CRDS en CASA zijn niet aftrekbaar. Bij CAK-gerechtigdheid is er geen CSG en dus ook geen aftrek.' },

{ id: 'p.fr.csg.rfr_grenzen_per_part', nl: 'RFR-grenzen per part voor het CSG-regime', fr: 'Seuils de revenu fiscal de référence par part', off: 'Seuils de RFR pour le taux de CSG applicable',
  reg: 'fr.csg', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld',
  w: { rfr_jaar: 2024, '1': [13048, 17057, 26472], '1.5': [16532, 21612, 33538], '2': [20016, 26167, 40604], '2.5': [23500, 30722, 47670], '3': [26984, 35277, 54736] },
  wv: 'van 13.048 / 17.057 / 26.472 euro bij 1 part tot 26.984 / 35.277 / 54.736 euro bij 3 parts',
  url: 'https://www.service-public.fr/particuliers/vosdroits/F2971',
  kn: 'service-public.fr, fiche F2971', bs: 'secundair: samenvattende fiche van service-public.fr, de wetsartikelen niet zelf gelezen',
  inst: 'DGFiP', vd: '2026-06-01', vdoor: DOOR_FKAI,
  freq: 'jaarlijks', lw: '2026-01-01', pub: 'voorjaar',
  in: [[ 'financieel-kompas-ai', 'config.json:119-147', 'reeks per part', false ]],
  opm: 'Het tarief voor 2026 hangt af van het revenu fiscal de référence over 2024.' },

{ id: 'p.fr.csg.opslag_per_halve_part', nl: 'Opslag per halve part boven drie parts', fr: 'Majoration par demi-part au-delà de trois parts', off: null,
  reg: 'fr.csg', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'EUR', jaar: '2026',
  st: 'vastgesteld', w: [3484, 4555, 7066], wv: '3.484 / 4.555 / 7.066 euro per halve part',
  url: 'https://www.service-public.fr/particuliers/vosdroits/F2971',
  kn: 'service-public.fr, fiche F2971', bs: 'secundair: samenvattende fiche van service-public.fr, de wetsartikelen niet zelf gelezen',
  inst: 'DGFiP', vd: '2026-06-01', vdoor: DOOR_FKAI, freq: 'jaarlijks', lw: '2026-01-01', pub: 'voorjaar',
  in: [[ 'financieel-kompas-ai', 'config.json:148-152', '3484 / 4555 / 7066', false ]] },

// --------------------------------------------------------------- prélèvements sociaux
{ id: 'p.fr.ps.taux_global', nl: 'Prélèvements sociaux op vermogen, totaaltarief', fr: 'Prélèvements sociaux sur les revenus du patrimoine', off: 'Prélèvements sociaux, taux global',
  reg: 'fr.ps', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026',
  st: 'vastgesteld', w: 0.172, wv: '17,2 procent',
  url: VT_PV_URL, kn: 'impots.gouv.fr, plus-value immobilière, bijgewerkt 7 juli 2026; opbouw CSG 9,2 plus CRDS 0,5 plus prélèvement de solidarité 7,5',
  bs: 'primair', inst: 'DGFiP', vd: VD_VT, vdoor: DOOR_VT,
  freq: 'zelden', lw: '2018-01-01', ingev: '2012-07-01', pub: 'wijziging alleen bij een loi de finances of een LFSS',
  hist: oud('0,172', 'zelfde waarde in de voorganger'),
  in: [[ 'financieel-kompas-ai', 'config.json:80', '0,172', false ],
       [ 'Vastgoedtransactie', 'calc.js:157', '17,2', false ],
       [ 'Plus-Value-Calculator', 'generate_pdf.py:87', '0,172', false ],
       [ 'cafeclaude', 'lib/domains/prompts/geld.ts:108', '17,2', false ]],
  uitz: ['Voor wie onder het arrest De Ruyter valt, blijft alleen het prélèvement de solidarité van 7,5 procent over. Zie p.xb.deruyter.prelevement_solidarite.'],
  test: { invoer: 'belastbare meerwaarde 100.000 euro', verwachte_uitkomst: '17.200 euro prélèvements sociaux', toelichting: 'Zonder toepassing van De Ruyter en zonder aftrek voor bezitsduur.' },
  opm: 'De meest verspreide parameter van het netwerk van platforms: vier aangesloten tools rekenen hiermee, allemaal met dezelfde waarde.' },

{ id: 'p.fr.ps.taux_roerend', nl: 'Prélèvements sociaux op roerend inkomen in de tool', fr: 'Prélèvements sociaux sur les revenus mobiliers', off: null,
  reg: 'fr.ps', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026',
  freq: 'zelden',
  in: [[ 'financieel-kompas-ai', 'config.json:81', '0,186', false ]],
  opm: 'Het bestand zet het tarief op roerend inkomen op 0,186 tegenover 0,172 op onroerend inkomen. Voor dat onderscheid staat geen bron in de repo. Verificatie tegen art. L136-6 en L136-7 CSS is nodig voordat hier een registerwaarde komt.' },

{ id: 'p.fr.ps.opbouw', nl: 'Opbouw van de prélèvements sociaux', fr: 'Composition des prélèvements sociaux', off: null,
  reg: 'fr.ps', klasse: 'overheid_vastgesteld', effect: 'informatief', eh: 'fractie', jaar: '2026',
  freq: 'zelden',
  in: [[ 'cafeclaude', 'lib/domains/prompts/geld.ts:108', 'CSG 9,2 plus CRDS 0,5 plus solidarité 7,5 is 17,2 procent', false ]],
  opm: 'De opbouw staat in het handboek maar zonder verificatiedatum bij de waarde. De uitkomst 17,2 procent staat wel vastgesteld, als p.fr.ps.taux_global. De niet-aangesloten begrippenlijst taalhulp-fr noemt dezelfde 17,2 procent; dat telt niet mee.' },

// --------------------------------------------------------------- sociale lasten per inkomenssoort
{ id: 'p.fr.sociaal.lasten_pensioen', nl: 'Sociale lasten op Frans pensioen, totaal', fr: 'Charges sociales sur pension, total', off: null,
  reg: 'fr.sociaal', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026', sot: 'csg_crds_casa',
  freq: 'jaarlijks', hist: oud('0,091'),
  in: [[ 'financieel-kompas-ai', 'config.json:76', '0,091', false ]],
  opm: 'Gelijk aan het totaal van het taux normal in p.fr.csg.tarief_per_regime, maar zonder eigen bron in het bestand. Verificatie moet uitwijzen of dit veld kan vervallen ten gunste van de regimetabel.' },

{ id: 'p.fr.sociaal.lasten_salaris', nl: 'Sociale lasten op salaris in Frankrijk', fr: 'Charges sociales sur salaire', off: null,
  reg: 'fr.sociaal', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026', sot: 'premie_werknemersverzekering',
  freq: 'jaarlijks', hist: oud('0,22'),
  in: [[ 'financieel-kompas-ai', 'config.json:77', '0,22', false ]],
  opm: 'Werknemersdeel, benaderd als een enkel percentage. De werkelijke opbouw kent meer dan tien afzonderlijke cotisations met eigen plafonds.' },

{ id: 'p.fr.sociaal.lasten_winst_diensten', nl: 'Sociale lasten op winst uit diensten', fr: 'Charges sociales sur prestations de services', off: 'Cotisations sociales micro-entrepreneur, prestations de services',
  reg: 'fr.sociaal', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026',
  freq: 'onregelmatig', lw: '2026-01-01', hist: [{ waarde: '0,123', geldig_jaar: '2025', herkomst: 'cafeclaude, lib/domains/prompts/geld.ts:84-85', opmerking: 'verhoogd naar 21,2 procent per 1 januari 2026' }],
  in: [[ 'financieel-kompas-ai', 'config.json:78', '0,212', false ],
       [ 'cafeclaude', 'lib/domains/prompts/geld.ts:84-85', '21,2 procent per 1 januari 2026', false ]],
  opm: 'Het handboek beschrijft de verhoging van 12,3 naar 21,2 procent per 1 januari 2026. Geen van beide repo\'s noemt een verificatiedatum bij de waarde.' },

{ id: 'p.fr.sociaal.lasten_winst_verhuur', nl: 'Sociale lasten op winst uit verhuur', fr: 'Charges sociales sur revenus locatifs meublés', off: null,
  reg: 'fr.sociaal', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'financieel-kompas-ai', 'config.json:79', '0,212', false ]] },

{ id: 'p.fr.urssaf.drempel_meuble_tourisme', nl: 'Urssaf-drempel verhuur meublé de tourisme', fr: 'Seuil Urssaf, meublé de tourisme', off: 'Seuil d\'affiliation, recettes brutes',
  reg: 'fr.urssaf', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR', jaar: '2026',
  freq: 'jaarlijks',
  in: [[ 'cafeclaude', 'lib/domains/prompts/geld.ts:75-76', '23000 euro bruto', false ]] },

{ id: 'p.fr.urssaf.drempel_chambres_hotes', nl: 'Urssaf-drempel chambres d\'hôtes', fr: 'Seuil Urssaf, chambres d\'hôtes', off: 'Seuil d\'affiliation, 13 procent du PASS',
  reg: 'fr.urssaf', klasse: 'afgeleid', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR', jaar: '2025',
  freq: 'jaarlijks',
  in: [[ 'cafeclaude', 'lib/domains/prompts/geld.ts:75-76', '6123 euro belastbaar', false ]],
  opm: 'Afgeleid van 13 procent van het plafond annuel de la sécurité sociale. Het handboek noemt het PASS-jaar 2025, terwijl de rest van het handboek 2026 is. Het PASS zelf staat nog niet in Peil.' },

{ id: 'p.fr.retraite.jaren_vereist', nl: 'Vereiste pensioenjaren Frankrijk', fr: 'Durée d\'assurance requise', off: 'Durée d\'assurance pour le taux plein',
  reg: 'fr.retraite', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', eh: 'jaren', jaar: '2026',
  freq: 'meerjaarlijks',
  in: [[ 'financieel-kompas-ai', 'config.json:10', '43', false ]],
  opm: 'De vereiste duur loopt op per geboortejaar. Een enkel getal dekt dat niet.' },

{ id: 'p.fr.retraite.opbouwpercentage', nl: 'Pensioenopbouwpercentage Frankrijk', fr: 'Taux de liquidation de la retraite de base', off: 'Taux plein',
  reg: 'fr.retraite', klasse: 'overheid_vastgesteld', effect: 'bepaalt_grondslag', eh: 'fractie', jaar: '2026',
  freq: 'zelden',
  in: [[ 'financieel-kompas-ai', 'config.json:11', '0,5', false ]] },

{ id: 'p.fr.retraite.gemiddeld_salaris_referentie', nl: 'Referentiesalaris voor de pensioenraming', fr: 'Salaire moyen de référence pour l\'estimation', off: null,
  reg: 'fr.retraite', klasse: 'indicatief', effect: 'bepaalt_grondslag', eh: 'EUR/jaar', jaar: '2026',
  freq: 'onbekend',
  in: [[ 'financieel-kompas-ai', 'config.json:9', '40000', false ]],
  opm: 'Een aanname van de tool, geen overheidsgrootheid. Het werkelijke salaire annuel moyen wordt per verzekerde berekend over de 25 beste jaren.' },

// --------------------------------------------------------------- impôt sur le revenu
{ id: 'p.fr.ir.schijven', nl: 'Schijven en tarieven impôt sur le revenu', fr: 'Barème de l\'impôt sur le revenu', off: 'Barème progressif, art. 197 CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR en fractie', jaar: '2026',
  freq: 'jaarlijks', pub: 'loi de finances, eind december, verwerkt in de fiches in het voorjaar',
  hist: oud('11497 / 29315 / 83823 / 180294', 'editie 2025, tarieven 0, 11, 30, 41 en 45 procent ongewijzigd'),
  in: [[ 'financieel-kompas-ai', 'config.json:157-177', '11600 / 29579 / 84577 / 181917 bij 0 / 11 / 30 / 41 / 45 procent', false ],
       [ 'cafeclaude', 'lib/domains/prompts/geld.ts:55', '11600 / 29579 / 84577 / 181917', false ]],
  opm: 'Rekentool en handboek zijn onderling gelijk. Geen van beide noemt een bron of verificatiedatum bij deze waarde; dit is de grootste ongeverifieerde grootheid van het register.' },

{ id: 'p.fr.ir.abattement_65plus', nl: 'Abattement voor 65-plussers', fr: 'Abattement pour personnes âgées de plus de 65 ans', off: 'Abattement spécial, art. 157 bis CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'EUR', jaar: '2026',
  freq: 'jaarlijks', hist: oud('17200 / 2746 / 27670 / 1373'),
  in: [[ 'financieel-kompas-ai', 'config.json:180-183', '17510 / 2796 / 28170 / 1398', false ]] },

{ id: 'p.fr.ir.abattement_pensioen', nl: 'Abattement op pensioen: tarief, minimum en maximum', fr: 'Abattement de 10 pour cent sur les pensions', off: 'Abattement de 10 pour cent, art. 158-5 CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'fractie en EUR', jaar: '2026',
  st: 'vastgesteld', w: { tarief: 0.1, minimum_per_persoon: 454, maximum_per_huishouden: 4439 },
  wv: '10 procent, minimaal 454 euro per persoon en maximaal 4.439 euro per huishouden',
  url: 'https://www.service-public.fr/particuliers/vosdroits/F415',
  kn: 'service-public.fr, fiche F415, Impôt sur le revenu: déclarer les pensions de retraite',
  bs: 'secundair: samenvattende fiche van service-public.fr, art. 158-5 CGI niet zelf gelezen',
  inst: 'DGFiP', vd: '2026-04-15', vdoor: DOOR_FKAI,
  freq: 'jaarlijks', lw: '2026-01-01', pub: 'service-public.fr werkt de fiche bij in april',
  in: [[ 'financieel-kompas-ai', 'config.json:190-192', '0,1 / 454 / 4439', false ]],
  opm: 'Minimum geldt per pensioengerechtigde, maximum per fiscaal huishouden. Het plafond wordt toegepast op de som van de per persoon berekende aftrekken.' },

{ id: 'p.fr.ir.abattement_loon', nl: 'Abattement op loon: tarief, minimum en maximum', fr: 'Abattement de 10 pour cent sur les salaires', off: 'Déduction forfaitaire pour frais professionnels',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'fractie en EUR', jaar: '2026',
  st: 'vastgesteld', w: { tarief: 0.1, minimum_per_persoon: 509, maximum_per_persoon: 14555 },
  wv: '10 procent, minimaal 509 euro en maximaal 14.555 euro per persoon',
  url: 'https://www.service-public.fr/particuliers/vosdroits/F1989',
  kn: 'service-public.fr, fiche F1989, Impôt sur le revenu: frais professionnels, forfait ou frais réels',
  bs: 'secundair: samenvattende fiche van service-public.fr, het wetsartikel niet zelf gelezen',
  inst: 'DGFiP', vd: '2026-04-15', vdoor: DOOR_FKAI,
  freq: 'jaarlijks', lw: '2026-01-01', pub: 'april',
  in: [[ 'financieel-kompas-ai', 'config.json:198-200', '0,1 / 509 / 14555', false ]],
  uitz: ['Wie hogere werkelijke beroepskosten heeft, kan kiezen voor frais réels. Die keuze vraagt een eigen afweging en bewijsstukken; leg die voor aan een belastingadviseur.'],
  opm: 'Anders dan bij pensioen gelden minimum en maximum hier per lid van het fiscale huishouden.' },

{ id: 'p.fr.ir.decote', nl: 'Décote: drempels, forfaits en percentage', fr: 'Décote de l\'impôt sur le revenu', off: 'Décote, art. 197 I-4 CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'heffingskorting', eh: 'EUR en fractie', jaar: '2026',
  kn: 'economie.gouv.fr, Pouvez-vous bénéficier de la décote de l\'impôt sur le revenu (inkomsten 2025, aanslag 2026); wettelijke grondslag art. 197 CGI',
  bs: 'secundair: voorlichtingspagina van economie.gouv.fr, art. 197 CGI niet zelf gelezen',
  inst: 'DGFiP', freq: 'jaarlijks', pub: 'voorjaar, bij de aangiftecampagne',
  in: [[ 'financieel-kompas-ai', 'config.json:206-210', '1982 / 3277 / 897 / 1483 / 0,4525', false ],
       [ 'cafeclaude', 'lib/domains/prompts/geld.ts:55', 'celibataire 1982 (897 min 45,25 procent), couple 3277 (1483 min 45,25 procent)', false ]],
  opm: 'De bron staat er wel, maar draagt geen verificatiedatum. Peil waardeert een ongedateerde bron niet stilzwijgend op tot een vastgestelde waarde. Toepassen na plafonnering van het gezinsquotient en voor belastingkortingen; de uitkomst kan niet negatief zijn.' },

{ id: 'p.fr.ir.quotient_plafond_per_halve_part', nl: 'Plafond gezinsquotient per halve part', fr: 'Plafonnement du quotient familial par demi-part', off: 'Plafonnement des effets du quotient familial',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', vt: 'plafond', eh: 'EUR', jaar: '2026',
  freq: 'jaarlijks', hist: oud(1759),
  in: [[ 'financieel-kompas-ai', 'config.json:188', '1807', false ]] },

{ id: 'p.fr.ir.pfu_tarief', nl: 'PFU, inkomstenbelastingdeel', fr: 'Prélèvement forfaitaire unique, part impôt sur le revenu', off: 'Prélèvement forfaitaire unique, art. 200 A CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'fractie', jaar: '2026',
  freq: 'zelden', ingev: '2018-01-01', hist: oud('0,128'),
  in: [[ 'financieel-kompas-ai', 'config.json:187', '0,128', false ],
       [ 'cafeclaude', 'lib/domains/prompts/geld.ts:143', '12,8 procent, totaal 30 procent', false ]],
  opm: 'Samen met de prélèvements sociaux van 17,2 procent komt het totaal op 30 procent. Dat totaal is een rekenuitkomst, geen eigen parameter.' },

{ id: 'p.fr.ir.abattement_micro_diensten', nl: 'Abattement micro op winst uit diensten', fr: 'Abattement micro, prestations de services', off: 'Abattement forfaitaire micro-BIC ou micro-BNC',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'fractie', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'financieel-kompas-ai', 'config.json:185', '0,5', false ]] },

{ id: 'p.fr.ir.abattement_micro_verhuur', nl: 'Abattement micro op winst uit verhuur', fr: 'Abattement micro, location meublée', off: null,
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'fractie', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'financieel-kompas-ai', 'config.json:186', '0,3', false ]],
  opm: 'Financieel Kompas kent het abattement wel maar niet het bijbehorende omzetplafond, waardoor de grens niet wordt bewaakt. Zie p.fr.micro.bic_verhuur.' },

{ id: 'p.fr.micro.abattement_per_categorie', nl: 'Abattement micro per categorie', fr: 'Abattement micro par catégorie', off: 'Abattement forfaitaire, art. 50-0 en 102 ter CGI',
  reg: 'fr.micro', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'procent', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'cafeclaude', 'lib/domains/prompts/geld.ts:85', '71 procent ventes, 50 procent prestations de services, 30 procent meublé non classé', false ]] },

{ id: 'p.fr.micro.plafonds', nl: 'Omzetplafonds micro-entreprise per categorie', fr: 'Plafonds de chiffre d\'affaires du régime micro', off: 'Seuils du régime micro, art. 50-0 CGI',
  reg: 'fr.micro', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'plafond', eh: 'EUR', jaar: '2026',
  freq: 'meerjaarlijks',
  in: [[ 'cafeclaude', 'lib/audit/prompts/ondernemen.ts:89', 'ventes 188700, prestations de services BIC 77700, BNC 77700', false ]] },

{ id: 'p.fr.micro.bic_verhuur', nl: 'Micro-BIC verhuur: plafond en abattement per type', fr: 'Micro-BIC location: plafond et abattement par type', off: 'Art. 50-0 CGI, meublés de tourisme et chambres d\'hôtes',
  reg: 'fr.micro', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'abattement', eh: 'EUR en procent', jaar: '2026',
  freq: 'onregelmatig',
  in: [[ 'cafeclaude', 'lib/domains/prompts/geld.ts:67-69', 'meublé niet geclassificeerd 15000 bij 30 procent; geclassificeerd en chambres d\'hôtes 77700 bij 50 procent', false ],
       [ 'gitekompas-fr', 'index.html:864-867', 'meublé non classé 30 procent bij 15000; meublé classé 50 procent bij 77700; chambre d\'hôtes 50 procent bij 77700; verhuur eigen woning 30 procent bij 15000', false ]],
  opm: 'Handboek en GiteKompas zijn onderling gelijk. GiteKompas noemt zijn eigen waarden V1 en indicatief.' },

{ id: 'p.fr.gite.degressieve_reeks', nl: 'Degressieve reeks per bezitsjaar in GiteKompas', fr: 'Série dégressive par année de détention', off: null,
  reg: 'fr.gite', klasse: 'indicatief', effect: 'verlaagt_last', vt: 'degressieve_aftrek', eh: 'procent', jaar: '2026',
  freq: 'onbekend',
  in: [[ 'gitekompas-fr', 'index.html:1177-1179', 'jaar 6: 75 procent; jaar 7: 50 procent; jaar 8: 25 procent', false ]],
  opm: 'De tool noemt deze reeks zelf indicatief. Welke wettelijke regeling erachter zit, is in de repo niet vastgelegd.' },

{ id: 'p.fr.gite.minimumheffing_niet_residenten', nl: 'Minimumheffing niet-residenten, bandbreedte', fr: 'Taux minimum d\'imposition des non-résidents', off: 'Taux minimum, art. 197 A CGI',
  reg: 'fr.gite', klasse: 'indicatief', effect: 'verhoogt_last', eh: 'procent', jaar: '2026',
  freq: 'jaarlijks',
  in: [[ 'gitekompas-fr', 'index.html:1226-1227', '20 tot 30 procent', false ]],
  uitz: ['Wie kan aantonen dat het gemiddelde tarief over het wereldinkomen lager is, mag dat tarief toepassen. Die berekening hoort bij een belastingadviseur.'],
  opm: 'De tool toont een bandbreedte in plaats van de wettelijke staffel met de grens waarboven 30 procent geldt.' },

{ id: 'p.fr.ifi.drempel', nl: 'IFI-drempel', fr: 'Seuil d\'assujettissement à l\'IFI', off: 'Seuil de 1.300.000 euros, art. 964 CGI',
  reg: 'fr.ifi', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR', jaar: '2026',
  freq: 'zelden', ingev: '2018-01-01', hist: oud(1300000, 'ongewijzigd tussen de twee edities'),
  in: [[ 'financieel-kompas-ai', 'config.json:217', '1300000', false ],
       [ 'cafeclaude', 'lib/domains/prompts/geld.ts:110', '1,3 miljoen euro', false ]] },

{ id: 'p.fr.ifi.schijven', nl: 'IFI-schijven en tarieven', fr: 'Barème de l\'IFI', off: 'Tarif de l\'IFI, art. 977 CGI',
  reg: 'fr.ifi', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR en fractie', jaar: '2026',
  freq: 'zelden', ingev: '2018-01-01',
  in: [[ 'financieel-kompas-ai', 'config.json:218-242', '800000 / 1300000 / 2570000 / 5000000 / 10000000 bij 0 tot 1,5 procent', false ]],
  opm: 'Het enige blok dat tussen de twee edities van Financieel Kompas ongewijzigd bleef.' },

{ id: 'p.fr.ir.credit_hulp_aan_huis_percentage', nl: 'Crédit d\'impôt hulp aan huis, percentage', fr: 'Crédit d\'impôt services à la personne, taux', off: 'Crédit d\'impôt, art. 199 sexdecies CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'belastingkrediet', eh: 'fractie', jaar: '2026',
  freq: 'zelden',
  in: [[ 'financieel-kompas-ai', 'config.json:245', '0,5', false ],
       [ 'ouderenzorg-fr', 'if-dossier/dossier-skelet.md:127', '50 procent', false ]] },

{ id: 'p.fr.ir.credit_hulp_aan_huis_plafond', nl: 'Crédit d\'impôt hulp aan huis, plafond', fr: 'Crédit d\'impôt services à la personne, plafond', off: 'Plafond de dépenses, art. 199 sexdecies CGI',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', vt: 'plafond', eh: 'EUR/jaar', jaar: '2026',
  freq: 'zelden',
  in: [[ 'financieel-kompas-ai', 'config.json:246', '12000', true ],
       [ 'ouderenzorg-fr', 'if-dossier/dossier-skelet.md:127', '6000 tot 10000', true ]],
  uitz: ['Het plafond kent verhogingen per kind ten laste en bij handicap. Welke variant in een concreet geval geldt, hoort bij een belastingadviseur.'],
  opm: 'De twee tools gebruiken verschillende plafonds voor dezelfde grootheid. Het percentage is wel gelijk. Welk plafond bedoeld is, basisplafond of een verhoogde variant, staat in geen van beide repo\'s.' },

{ id: 'p.fr.ir.boete_niet_aangifte_buitenlandse_rekening', nl: 'Boete niet-aangifte buitenlandse rekening', fr: 'Amende pour compte étranger non déclaré', off: 'Amende, art. 1736 IV CGI, formulaire 3916',
  reg: 'fr.ir', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'EUR/jaar', jaar: '2026',
  freq: 'zelden',
  in: [[ 'cafeclaude', 'lib/domains/prompts/geld.ts:10', '1500 euro per jaar', false ]] },

{ id: 'p.fr.acre.reductie_en_duur', nl: 'ACRE: reductie en duur', fr: 'ACRE: taux et durée', off: 'Aide à la création ou reprise d\'entreprise',
  reg: 'fr.acre', klasse: 'overheid_vastgesteld', effect: 'verlaagt_last', eh: 'procent en maanden', jaar: '2026',
  freq: 'onregelmatig',
  aank: { datum: '2026-07-01', omschrijving: 'Mogelijke verlaging van de reductie van 50 naar 25 procent', bron: 'cafeclaude, lib/audit/prompts/ondernemen.ts:98-100' },
  in: [[ 'cafeclaude', 'lib/audit/prompts/ondernemen.ts:98-100', '50 procent gedurende 12 maanden', false ]] },

{ id: 'p.fr.cvae.drempel', nl: 'CVAE-drempel', fr: 'Seuil de la CVAE', off: 'Cotisation sur la valeur ajoutée des entreprises',
  reg: 'fr.cvae', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR', jaar: '2026',
  freq: 'onregelmatig',
  aank: { datum: '2030-01-01', omschrijving: 'Afschaffing van de CVAE, uitgesteld naar 2030', bron: 'cafeclaude, lib/audit/prompts/ondernemen.ts:72' },
  in: [[ 'cafeclaude', 'lib/audit/prompts/ondernemen.ts:72', '152500 euro omzet', false ]] },

{ id: 'p.fr.lmp.drempel', nl: 'LMP-drempel', fr: 'Seuil du statut de loueur en meublé professionnel', off: 'Art. 155 IV CGI',
  reg: 'fr.lmp', klasse: 'overheid_vastgesteld', effect: 'bepaalt_toepasselijkheid', vt: 'drempel', eh: 'EUR', jaar: '2026',
  freq: 'zelden',
  in: [[ 'cafeclaude', 'lib/audit/prompts/ondernemen.ts:103', '23000 euro', false ]],
  opm: 'De tweede voorwaarde, dat de huuropbrengst de overige beroepsinkomsten overtreft, staat niet als aparte grootheid in de repo.' },

{ id: 'p.fr.tva.tarief_algemeen', nl: 'Btw-tarief Frankrijk, algemeen', fr: 'Taux normal de TVA', off: 'Taux normal, art. 278 CGI',
  reg: 'fr.tva', klasse: 'overheid_vastgesteld', effect: 'verhoogt_last', eh: 'procent', jaar: '2026',
  freq: 'zelden', ingev: '2014-01-01',
  in: [[ 'Vastgoedtransactie', 'calc.js:104', '20,0', false ]],
  opm: 'Vastgoedtransactie noteert bij deze post uitdrukkelijk dat er geen eigen wetsartikel is: het algemene tarief geldt omdat de emolumenten een dienst zijn. De niet-aangesloten btw-tool ca-btw-oss-tool voert hetzelfde tarief met bron en datum; die repo is niet aangesloten, dus dat telt hier niet als verificatie.' },
];
